# Generated by Django 2.2.14 on 2021-10-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='orderId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
