# Generated by Django 2.2.14 on 2021-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20211022_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='address_type',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='orderPlaced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
