# Generated by Django 2.2.14 on 2021-10-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20211022_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='fullName',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
